### ISSUE TITLE
Migration from vault.pkiSecret.SecretBackend to vault.Mount results in resource replacement

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-vault#181]
### What happened?

Customer wanted to upgrade this vault provider from pre-5.0 to 5.0.0 (or higher). In v5.0.0, it includes v4 of the upstream TF provider which has the `vault_pki_secret_backend` resource removed in favor of `vault_mount`. The TF migration guide has an example on how to replace the old resource with the new one:

```hcl
resource "vault_mount" "pki-example" {
  path        = "pki-example"
  type        = "pki"
  description = "This is an example PKI mount"

  default_lease_ttl_seconds = 3600
  max_lease_ttl_seconds     = 86400
}
```
Source: https://registry.terraform.io/providers/hashicorp/vault/latest/docs/guides/version_3_upgrade#deprecated-resource

Now, the `type` property is a new property, which in our case leads to the problem.

Customer updates their Pulumi code from:

```python
pulumi_vault.pkisecret.SecretBackend("test-root-ca", path="pki/root-ca")
```

to

```python
pulumi_vault.Mount("test-root-ca", path="pki/root-ca", type="pki", opts=ResourceOptions(aliases=["(old urn)"]))
```

Pulumi wants to replace the resource:

```
+-vault:index/mount:Mount: (replace)
    [id=(redacted id)]
    [urn=(redacted urn)]
    [provider: (redacted urn]
  + type: "pki"
```

This is probably due to the `type` being set as a "new" property, while this is just needed to complete the setup of the migrated resource.

### Steps to reproduce

- Use a pre-v5 provider to create the old `vault.pkiSecret.SecretBackend` resource.
- Upgrade the provider to V5 or beyond
- Update the code and replace the old type with the new type like in the section above
- Run `pulumi preview` to see Pulumi suggest to replace the resource

### Expected Behavior

Pulumi should update the type of the resource to `vault.Mount` in the state and record it is a `pki` type mount.

### Actual Behavior

Because the `type` is set, and it wasn't set before, this is recorded as a breaking change and Pulumi suggests to replace the Mount resource.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @ringods 

Sorry for the silence here - we started discussing this in engineering at the end of last week

Paul

**Comment by mikhailshilkov** [comment]
@ringods Is this issue still useful or should we close it? It's been in `awaiting-feedback` for a while, but I'm not sure what we are waiting for.

**Comment by MitchellGerdisch** [comment]
I have a customer running into this same issue.

**Comment by MitchellGerdisch** [comment]
After digging into this a bit, the referenced terraform doc does not appear to be saying things are automatically migrated. It's just showing what an analogous `Mount` resource would look like. 

Here are steps that can be used to do the migration:
NOTE: You can do these steps using version 4.6.0 of the provider and then once everything is looking good, you can upgrade to 5.13.0.
 
- Add the `retain_on_delete=True` resource option to the existing `SecretBackend` resource.
   - See: https://www.pulumi.com/docs/concepts/options/retainondelete/
- Run `pulumi up` to get the setting into state.
- Add a `Mount` resource to your code that uses the same variable name and resource name and properties as the original `SecretBackend` resource.
- For that new `Mount` resource include the `import` resource option pointing to the path of the original `SecretBackend` resource.
  - See: https://www.pulumi.com/docs/concepts/options/import/ 
- Comment out or otherwise remove the original `SecretBackend` resource from the code.
- Run `pulumi preview` to confirm that although the old resource is going to be deleted (but retained) and a new mount resource created, nothing is being replaced or changed due to the new Mount resource.
- Run `pulumi up` to update the state
- Remove the `import` resource option 
- Run `pulumi up` again to update the state

-----
If for some reason your use-case is not compatible with the above sequence you can use these steps instead.
Of course, since it includes modifying the state file directly, care must be taken.

- Starting with the current stack containing the SecretBackend resource export the stack state (e.g. `pulumi stack export --file stack.json`)
- Find the SecretBackend resource(s) and ADD `"type": "pki"` to the "outputs" section of the resource(s)
- import the modified state (e.g. `pulumi stack import --file stack.json`)
- Now modify the Pulumi program such that you:
   - Add a `Mount` resource that aliases the URN for the `SecretBackend` resource.
     - USE the same variable and resource name as the old `SecretBackend` resource so downstream references still work.
   - You can find the URN in Pulumi Cloud or in the state file. 
   - For example:
 ```
mount_pkisecret = vault.Mount("pkiMountExample", 
    default_lease_ttl_seconds=43200,
    description="My PKI Backend",
    max_lease_ttl_seconds=43200,
    path="pki2",
    type="pki",
    opts=pulumi.ResourceOptions(
        aliases=["urn:pulumi:STACKNAME::PROJECTNAME::vault:pkiSecret/secretBackend:SecretBackend::pkiMountExample"],
    )
)
```
- Comment out or otherwise remove the old SecretBackend resource
- Run `pulumi preview` to validate that the SecretBackend and/or Mount resources are not replaced.
- Run `pulumi up` to update state with the change.
- Remove the alias
- Run `pulumi up`
