### ISSUE TITLE
Upgrade provider failure: June 27, 2023 @ 14:57

### ISSUE THREAD

**Issue by aq17** [pulumi/pulumi-vault#270]
View the latest workflow run: https://github.com/pulumi/pulumi-vault/actions/runs/5394963430

**Comment by AaronFriel** [comment]
Is this related to #197, @aq17 @iwahbe?

**Comment by iwahbe** [comment]
I can't say for certain since the workflow link just says "the job was skipped". #269 failed because it didn't have permissions to access the forked branch, so that would be my guess for this failure as well. 

I think the immediate fix is to allow this workflow to access `pulumi-terraform-vault`. Ultimately, this is because of #197, since it prevents us upgrading the bridge enough to migrate from a forked to a patched workflow (removing this problem).
